### ISSUE TITLE
Username and password requirement before posting

### ISSUE THREAD

**Issue by segallagher** [nidamon/CS372#28]
Would like a display of what is required of a password and username before pressing submit. Does not have to be dynamic in any way, just a list would work.

**Comment by Willg3D** [comment]
I have added a button that allows users to see requirements. If you use my hosted server to see it, you will notice the requirements text alignment is center instead of left aligned, this is a weird issue with my server, and I believe Cloudflare (so it is not representative of a genuine issue). 

Other than that, please review it and leave any feedback.

**Comment by bfforsythe** [comment]
looks good! you spelled requirements wrong though :)

**Comment by segallagher** [comment]
The text alignment is left on local hosting. requirements are present
